# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Getaway' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Getaway
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FacebookCore'
  pod 'Firebase/Storage'
  pod 'FacebookLogin'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'JSQMessagesViewController'
  pod 'PopupDialog', '~> 0.9'
  pod 'GooglePlaces'
  pod 'GoogleMaps'

  target 'GetawayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetawayUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
